In [ ]:
# Repo code 01
import requests
import json
import pandas as pd

url = 'https://helmboots.com/products.json?limit=100&page=1'
r = requests.get(url)

data = r.json()

product_list = []

for item in data['products']:
  title = item['title']
  handle = item['handle']
  product_type = item['product_type']
  for image in item['images']:
    try:
      image = image['src']
    except:
      image = 'None'
  #print(image['src'])
  for variant in item['variants']:
    position = variant['position']
    product_id = variant['product_id']
    sku = variant['sku']
    price = variant['price']
    grams = variant['grams']
    available = variant['available']
    created_at = variant['created_at']
    updated_at = variant['updated_at']
# print(image,title,handle,product_type,position,product_id,sku,price,grams,available,created_at,updated_at)
    product = {
        'sku':sku,
        'product_id':product_id,
        'image':image,
        'title':title,
        'hanle':handle,
        'product_type':product_type,
        'position':position,
        'price':price,
        'grams':grams,
        'available':available,
        'created_at':created_at,
        'updated_at':updated_at
    }

    product_list.append(product)

In [ ]:
  df = pd.DataFrame(product_list)
  df

             sku  ...                 updated_at
0     H002022006  ...  2021-11-18T16:56:45-06:00
1     H002022007  ...  2021-05-13T07:11:55-05:00
2     H002022075  ...  2021-04-09T05:19:35-05:00
3     H002022008  ...  2021-05-02T22:16:25-05:00
4     H002022085  ...  2021-11-18T16:56:45-06:00
...          ...  ...                        ...
1807              ...  2021-12-22T12:17:01-06:00
1808              ...  2021-12-22T22:00:20-06:00
1809       10253  ...  2021-12-31T22:18:46-06:00
1810  OTTRWX_006  ...  2022-01-07T12:37:21-06:00
1811       10252  ...  2022-01-07T10:24:26-06:00

[1812 rows x 12 columns]

In [ ]:
# Repo code 02
response = urlopen("https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ETC")
json_data = response.read().decode('utf-8', 'replace')

d = json.loads(json_data)
df = pd.json_normalize(d['result'])
df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])
df = df.set_index('TimeStamp')

print(df.head())

                                Id  ...                                  Uuid
TimeStamp                           ...
2022-01-12 05:53:17.350  321196134  ...  9a5f2231-7669-4811-b77a-d356cc1c0126
2022-01-12 05:40:09.760  321192603  ...  d0ba9f1c-df91-4ef3-bf17-f0cbb4503a50
2022-01-12 05:26:01.070  321189086  ...  5d8d6c4c-36f8-4f38-92b0-5490b07e7cf3
2022-01-12 05:23:45.710  321188556  ...  17831346-7c88-41f5-b647-c413e3cbfbb0
2022-01-12 04:37:10.700  321177341  ...  3217b4d4-327d-4ef7-8fd8-427b192e2a41

[5 rows x 7 columns]

In [ ]:
# Repo code 03
df = pd.read_json('https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ETC')
df = pd.DataFrame(df['result'].values.tolist())
df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])
df = df.set_index('TimeStamp')

df.head()

                                Id  ...                                  Uuid
TimeStamp                           ...
2022-01-12 05:53:17.350  321196134  ...  9a5f2231-7669-4811-b77a-d356cc1c0126
2022-01-12 05:40:09.760  321192603  ...  d0ba9f1c-df91-4ef3-bf17-f0cbb4503a50
2022-01-12 05:26:01.070  321189086  ...  5d8d6c4c-36f8-4f38-92b0-5490b07e7cf3
2022-01-12 05:23:45.710  321188556  ...  17831346-7c88-41f5-b647-c413e3cbfbb0
2022-01-12 04:37:10.700  321177341  ...  3217b4d4-327d-4ef7-8fd8-427b192e2a41

[5 rows x 7 columns]