# **Web scraping Shopify - easily download all products**
**Link tutorial**: https://youtu.be/jPjxWC7zV2s<br>
**Link source for scraping**: https://helmboots.com/<br>
> **Link json**: 
- https://helmboots.com/products.json
- https://helmboots.com/products.json?limit=250&page=1

In [ ]:
import pandas as pd
import numpy as np
import requests
import json

from urllib.request import urlopen

In [ ]:
# Python web scraping:JSON - No.1

url = 'https://helmboots.com/products.json?limit=100&page=1'
r = requests.get(url)

data = r.json()

product_list = []

for item in data['products']:
  title = item['title']
  handle = item['handle']
  product_type = item['product_type']
  
  for image in item['images']:
    try:
      image = image['src']
    except:
      image = 'None'

  for variant in item['variants']:
    position = variant['position']
    product_id = variant['product_id']
    sku = variant['sku']
    price = variant['price']
    grams = variant['grams']
    available = variant['available']
    created_at = variant['created_at']
    updated_at = variant['updated_at']

    product = {
        'sku':sku,
        'product_id':product_id,
        'image':image,
        'title':title,
        'hanle':handle,
        'product_type':product_type,
        'position':position,
        'price':price,
        'grams':grams,
        'available':available,
        'created_at':created_at,
        'updated_at':updated_at
    }

    product_list.append(product)

In [ ]:
#Change list into dataframe
helmboots_shopify = pd.DataFrame(product_list)

#Remove duplicate data
helmboots_shopify['title'].drop_duplicates()

0                                The Railroad
27                           The Muller Brown
54                           The Marion Olive
81                           The Muller Black
108                           The Muller Teak
                        ...
1774                          The Pablo Black
1801                                Gift Card
1809    Otter Wax Saddle Soap Leather Cleaner
1810     Otter Wax Boot Wax - Leather Sealant
1811      Otter Wax Leather Salve Conditioner
Name: title, Length: 99, dtype: object

In [ ]:
helmboots_shopify

             sku  ...                 updated_at
0     H002022006  ...  2021-11-18T16:56:45-06:00
1     H002022007  ...  2021-05-13T07:11:55-05:00
2     H002022075  ...  2021-04-09T05:19:35-05:00
3     H002022008  ...  2021-05-02T22:16:25-05:00
4     H002022085  ...  2021-11-18T16:56:45-06:00
...          ...  ...                        ...
1807              ...  2021-12-22T12:17:01-06:00
1808              ...  2021-12-22T22:00:20-06:00
1809       10253  ...  2021-12-31T22:18:46-06:00
1810  OTTRWX_006  ...  2022-01-07T12:37:21-06:00
1811       10252  ...  2022-01-07T10:24:26-06:00

[1812 rows x 12 columns]

In [ ]:
# Python web scraping:JSON - No.2
response = urlopen("https://helmboots.com/products.json?limit=100&page=1")
json_data = response.read().decode('utf-8', 'replace')
d = json.loads(json_data)
df = pd.json_normalize(d['products'])

df.head(2)

          id  ...                                            options
0   99414168  ...  [{'name': 'Size', 'position': 1, 'values': ['6...
1  334557149  ...  [{'name': 'Size', 'position': 1, 'values': ['6...

[2 rows x 13 columns]

In [ ]:
# Python web scraping:JSON - No.3
df = pd.read_json('https://helmboots.com/products.json?limit=100&page=1')
df_helmboots = pd.DataFrame(df['products'].values.tolist())
df_helmboots.head(2)

          id  ...                                            options
0   99414168  ...  [{'name': 'Size', 'position': 1, 'values': ['6...
1  334557149  ...  [{'name': 'Size', 'position': 1, 'values': ['6...

[2 rows x 13 columns]